name: Test

on:
  push:
    branches:
    - master
  pull_request:
    #schedule:
    # monthly
    #- cron: "0 0 1 * *"

env:
  #bump to clear caches
  ACTION_CACHE_VERSION: 'v1'

jobs:
  setup:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3
      - uses: actions/cache@v2
        with:
          path: ~/.m2/repository
          key: ${{ env.ACTION_CACHE_VERSION }}-${{ runner.os }}-maven-${{ hashFiles('**/deps.edn') }}
      - name: Prepare java
        uses: actions/setup-java@v2
        with:
          distribution: 'temurin'
          java-version: 11
      - name: Install clojure tools
        uses: DeLaGuardo/setup-clojure@3.5
        with:
          lein: 2.9.8
      - name: Check dependabot is in sync with project.clj
        run: |
          ./script/sync-dependabot
          git diff --exit-code dependabot/pom.xml
  test:
    needs: setup
    strategy:
      matrix:
        java: ['8', '11', '17']
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3
      - uses: actions/cache@v2
        with:
          path: ~/.m2/repository
          key: ${{ env.ACTION_CACHE_VERSION }}-${{ runner.os }}-maven-${{ hashFiles('**/deps.edn') }}
      - name: Prepare java
        uses: actions/setup-java@v2
        with:
          distribution: 'temurin'
          java-version: ${{ matrix.java }}
      - name: Install clojure tools
        uses: DeLaGuardo/setup-clojure@3.5
        with:
          lein: 2.9.8
      - run: lein test
